### ISSUE TITLE
imagergb doesn't work on externally loaded images

### ISSUE THREAD

**Issue by BernhardWerner** [CindyJS/CindyJS#849]
When I load an image from my hard drive, the command `imagergb` results in an empty array and the error messages below. Calling it on an image texture created through code, it works fine. 

On Chrome and Edge, the error message is
```
DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at Jb (https://cindyjs.org/dist/v0.8/Cindy.js:408:269)
    at Object.q.imagergba$4 (https://cindyjs.org/dist/v0.8/Cindy.js:748:232)
    at q.imagergb$4 (https://cindyjs.org/dist/v0.8/Cindy.js:748:323)
    at Object.evaluate (https://cindyjs.org/dist/v0.8/Cindy.js:579:447)
    at w (https://cindyjs.org/dist/v0.8/Cindy.js:417:104)
    at Object.evaluate (https://cindyjs.org/dist/v0.8/Cindy.js:579:333)
    at w (https://cindyjs.org/dist/v0.8/Cindy.js:417:104)
    at q.println$1 (https://cindyjs.org/dist/v0.8/Cindy.js:596:496)
    at Object.evaluate (https://cindyjs.org/dist/v0.8/Cindy.js:579:447)
    at w (https://cindyjs.org/dist/v0.8/Cindy.js:417:104)
```

On Firefox it simply is `DOMException: The operation is insecure.`

**For an MWE:**
With the setup
```
<script id='init' type='text/x-cindyscript'>
createimage("created", 446, 115);
colorplot([0, 0], [1, 0], "created", 0.5);
</script>


<script>
  cindy = createCindy({canvasname:"CSCanvas",
                drawscript:"draw",
                initscript:"init",
                images: {
                   loaded: "img1.png"
                }
               });
  
</script>
```

the code

```
<script id='draw' type='text/x-cindyscript'>
  println(imagergb([0,0], [446,0], "created", [4, 4], interpolate->false, repeat->false));
</script>
```
gives the expected result of `[0.5, 0.5, 0.5]`. However, the code
```
<script id='draw' type='text/x-cindyscript'>
  println(imagergb([0, 0], [446, 0], "loaded", [4, 4], interpolate->false, repeat->false));
</script>
```
results in the error messages above plus `[]` as a console output.

**Comment by kortenkamp** [comment]
Well, this probably works as expected – I have no idea how we could allow a local html file to load local resources and inspect them. Sounds like a security restriction that must not be circumvented. Unless you have an idea why this should be possible or can provide an example of an html that uses javascript to do this, I think we have to close this. Feel free to reopen if you disagree.
